version: '3'

services:

  redis:
    container_name: starkman-redis
    image: redis
    ports:
      - "6380:6379"
    restart: always
    build:
      context: Starkman.Backend.Storage/Redis
      dockerfile: Dockerfile
    networks:
      - starkman-backend
      
networks:
  starkman-backend: