version: '3'

services:

  redis:
    container_name: starkman-redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    build:
      context: Starkman.Backend.Storage/Redis
      dockerfile: Dockerfile
    networks:
      - starkman-backend

  webapi:
    container_name: starkman-api
    image: webapi
    ports:
      - "8080:80"
    restart: always
    build:
      context: Starkman.Backend.WebApi
      dockerfile: Dockerfile
    networks:
     - starkman-backend
    depends_on: 
      - redis
      
networks:
  starkman-backend: